import { Layout } from 'antd';
import React from 'react';

import Header from '../Header/Header';

const { Content, Footer } = Layout;

const Contents = (props: any) => {
  const { clickToCollapse, collapse } = props;
  return (
    <Layout style={{ marginLeft: collapse ? '' : 200 }}>
      <Header clickToCollapse={clickToCollapse} collapse={collapse} />
      <Content style={{ margin: '24px 0', padding: 24 }}>
        <div style={{ padding: 24, textAlign: 'center' }}>
          ...j
          <br />
          Really ReallyReally ReallyReally ReallyReally ReallyReally
          ReallyReally ReallyReally ReallyReally ReallyReally ReallyReally
          ReallyReally ReallyReally ReallyReally ReallyReally ReallyReally
          ReallyReally ReallyReally ReallyReally ReallyReally ReallyReally
          ReallyReally ReallyReally ReallyReally ReallyReally ReallyReally
          Really
          <br />
          ...
          <br />
          ...
          <br />
          ...
          <br />
          long
          <br />
          ...
          <br />
          ...
          <br />
          ...
          <br />
          ...
          <br />
          ...
          <br />
          ...
          <br />
          ...
          <br />
          ...
          <br />
          ...
          <br />
          ...
          <br />
          ...
          <br />
          ...
          <br />
          ...
          <br />
          ...
          <br />
          ...
          <br />
          ...
          <br />
          ...
          <br />
          ...
          <br />
          ...
          <br />
          ...
          <br />
          ...
          <br />
          ...
          <br />
          ...
          <br />
          ...
          <br />
          ...
          <br />
          ...
          <br />
          ...
          <br />
          ...
          <br />
          ...
          <br />
          ...
          <br />
          ...
          <br />
          ...
          <br />
          ...
          <br />
          ...
          <br />
          ...
          <br />
          ...
          <br />
          ...
          <br />
          ...
          <br />
          ...
          <br />
          ...
          <br />
          ...
          <br />
          content
        </div>
      </Content>
      <Footer style={{ textAlign: 'center' }}>
        Ant Design ©2018 Created by Ant UED
      </Footer>
    </Layout>
  );
};

export default Contents;
