
// USERS ---------

// USER LOGIN
export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE';

// GET USERS
export const GET_USERS = 'GET_USERS ';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const GET_USERS_FAILURE = 'GET_USERS_FAILURE';

// ROLES ----------

// GET ROLES
export const GET_ROLES = 'GET_ROLES';
export const GET_ROLES_SUCCESS = 'GET_ROLES_SUCCESS';
export const GET_ROLES_FAILURE = 'GET_ROLES_FAILURE';

// GET ROLE
export const GET_ROLE = 'GET_ROLE';
export const GET_ROLE_SUCCESS = 'GET_ROLE_SUCCESS';
export const GET_ROLE_FAILURE = 'GET_ROLE_FAILURE';

// ASSIGN ROLE
export const ASSIGN_ROLE = 'ASSIGN_ROLE';
export const ASSIGN_ROLE_SUCCESS = 'ASSIGN_ROLE_SUCCESS';
export const ASSIGN_ROLE_FAILURE = 'ASSIGN_ROLE_FAILURE';

// DELETE ASSIGNED USER ROLE
export const DELETE_ASSIGNED_ROLE = 'DELETE_ASSIGNED_ROLE';
export const DELETE_ASSIGNED_ROLE_SUCCESS = 'DELETE_ASSIGNED_ROLE_SUCCESS';
export const DELETE_ASSIGNED_ROLE_FAILURE = 'DELETE_ASSIGNED_ROLE_FAILURE';
